import Footer from "@/app/_components/Layout/Footer"
import "../sass/main.scss"
import Header from "@/app/_components/Layout/Header"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
